### ISSUE TITLE
[🚫 Bug] Corrupted install after bump to v7.3.0

### ISSUE THREAD

**Issue by djelinek** [redhat-developer/vscode-extension-tester#1215]
### Describe the bug

-

### Steps to reproduce

```Shell
npm install after upgrade to ExTester 7.3.0
```

### Logs

```Shell
test/ui/common/conditions.ts:6:103 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'WebDriver'.
6 import { BottomBarPanel, /*InputBox,*/ Notification, NotificationType, /*ViewItem,*/ /*ViewSection,*/ WebDriver, Workbench } from 'vscode-extension-tester';
                                                                                                        ~~~~~~~~~
test/ui/common/conditions.ts:60:20 - error TS2339: Property 'getDriver' does not exist on type 'TerminalView'.
60     await terminal.getDriver().wait(async () => {
                      ~~~~~~~~~
test/ui/suite/component.ts:8:30 - error TS2305: Module '"../common/conditions"' has no exported member 'itemExists'.
8 import { notificationExists, itemExists, terminalHasText } from '../common/conditions';
                               ~~~~~~~~~~
test/ui/suite/component.ts:78:32 - error TS2339: Property 'click' does not exist on type 'WelcomeContentButton'.
78             await newComponent.click();
                                  ~~~~~
test/ui/common/overdrives.ts:5:23 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'By'.
5 import { ViewSection, By, waitForAttributeValue } from 'vscode-extension-tester';
                        ~~
test/ui/common/overdrives.ts:12:45 - error TS2339: Property 'findElement' does not exist on type 'ViewSection'.
12             const mainPanel = await section.findElement(By.className('pane-header'));
                                               ~~~~~~~~~~~
test/ui/common/overdrives.ts:13:46 - error TS2339: Property 'findElement' does not exist on type 'ViewSection'.
13             const arrowPanel = await section.findElement(By.className('codicon'));
                                                ~~~~~~~~~~~
test/ui/common/overdrives.ts:15:27 - error TS2339: Property 'getDriver' does not exist on type 'ViewSection'.
15             await section.getDriver().wait(waitForAttributeValue(mainPanel, 'aria-expanded', 'false'), 2_000);
                             ~~~~~~~~~
test/ui/suite/login.ts:9:30 - error TS2305: Module '"../common/conditions"' has no exported member 'itemExists'.
9 import { notificationExists, itemExists } from '../common/conditions';
                               ~~~~~~~~~~
test/ui/suite/login.ts:36:31 - error TS2339: Property 'click' does not exist on type 'WelcomeContentButton'.
36             await loginButton.click();
                                 ~~~~~
test/ui/suite/login.ts:67:26 - error TS2339: Property 'click' does not exist on type 'ViewPanelAction'.
67             await action.click();
                            ~~~~~
test/ui/common/ui/webview/newComponentWebViewEditor.ts:5:10 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'By'.
5 import { By, Key, WebElement, WebView } from 'vscode-extension-tester';
           ~~
test/ui/common/ui/webview/newComponentWebViewEditor.ts:5:14 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'Key'.
5 import { By, Key, WebElement, WebView } from 'vscode-extension-tester';
               ~~~
test/ui/common/ui/webview/newComponentWebViewEditor.ts:5:19 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'WebElement'.
5 import { By, Key, WebElement, WebView } from 'vscode-extension-tester';
                    ~~~~~~~~~~
test/ui/common/ui/webview/registryWebViewEditor.ts:5:10 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'By'.
5 import { By, ModalDialog, WebElement, WebView } from 'vscode-extension-tester';
           ~~
test/ui/common/ui/webview/registryWebViewEditor.ts:5:27 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'WebElement'.
5 import { By, ModalDialog, WebElement, WebView } from 'vscode-extension-tester';
                            ~~~~~~~~~~
test/ui/suite/createComponent.ts:172:27 - error TS2339: Property 'click' does not exist on type 'ViewPanelAction'.
172             await refresh.click();
                              ~~~~~
test/ui/suite/createComponent.ts:177:26 - error TS2339: Property 'click' does not exist on type 'WelcomeContentButton'.
177             await button.click();
                             ~~~~~
test/ui/suite/devfileRegistries.ts:6:101 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'WebDriver'.
6 import { ActivityBar, CustomTreeSection, EditorView, InputBox, SideBarView, ViewSection, VSBrowser, WebDriver } from 'vscode-extension-tester';
                                                                                                      ~~~~~~~~~
test/ui/suite/devfileRegistries.ts:35:35 - error TS2339: Property 'getText' does not exist on type 'ViewItem'.
35             expect(await registry.getText()).to.equal('DefaultDevfileRegistry');
                                     ~~~~~~~
test/ui/suite/devfileRegistries.ts:41:29 - error TS2339: Property 'click' does not exist on type 'ViewPanelAction'.
41             await addAction.click();
                               ~~~~~
test/ui/suite/devfileRegistries.ts:106:75 - error TS2339: Property 'click' does not exist on type 'ViewPanelAction'.
106             await (await registrySection.getAction('Open Registry View')).click();
                                                                              ~~~~~
test/ui/suite/focusOn.ts:7:23 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'By'.
7 import { ActivityBar, By, SideBarView, waitForAttributeValue } from 'vscode-extension-tester'
                        ~~
test/ui/suite/focusOn.ts:25:57 - error TS2339: Property 'findElement' does not exist on type 'ViewSection'.
25                         const mainPanel = await section.findElement(By.className('pane-header'));
                                                           ~~~~~~~~~~~
test/ui/suite/focusOn.ts:26:58 - error TS2339: Property 'findElement' does not exist on type 'ViewSection'.
26                         const arrowPanel = await section.findElement(By.className('codicon'));
                                                            ~~~~~~~~~~~
test/ui/suite/focusOn.ts:28:39 - error TS2339: Property 'getDriver' does not exist on type 'ViewSection'.
28                         await section.getDriver().wait(waitForAttributeValue(mainPanel, 'aria-expanded', 'false'), 2_000);
                                         ~~~~~~~~~
test/ui/common/ui/webview/ServerlessFunctionWebViewEditor.ts:5:10 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'By'.
5 import { By, InputBox, Key, WebElement, WebView } from 'vscode-extension-tester';
           ~~
test/ui/common/ui/webview/ServerlessFunctionWebViewEditor.ts:5:24 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'Key'.
5 import { By, InputBox, Key, WebElement, WebView } from 'vscode-extension-tester';
                         ~~~
test/ui/common/ui/webview/ServerlessFunctionWebViewEditor.ts:5:29 - error TS2305: Module '"vscode-extension-tester"' has no exported member 'WebElement'.
5 import { By, InputBox, Key, WebElement, WebView } from 'vscode-extension-tester';
                              ~~~~~~~~~~
test/ui/suite/serverlessFunction.ts:44:32 - error TS2339: Property 'click' does not exist on type 'ViewPanelAction'.
44             await createButton.click();
                                  ~~~~~
test/ui/suite/serverlessFunction.ts:62:33 - error TS2339: Property 'click' does not exist on type 'ViewPanelAction'.
62             await refreshButton.click();
                                   ~~~~~
Found 31 errors.
```

### Operating System

all

### Visual Studio Code

-

### vscode-extension-tester

7.3.0

### NodeJS

18.x
